# Generated by Django 4.2.2 on 2023-07-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='data_of_news',
            new_name='date_of_news',
        ),
    ]
